
client_id: '661634338152-6530bf42h86ohpjtmitli5ct8cp8cq8g.apps.googleusercontent.com'
client_secret: 'g-o1vAeFstijR3OmGc41_Ot-'

cartodb_api_key: 'a18e584210565ef6dc018c76e40e59cd0c9a2a22'
cartodb_user: 'albafjez'

geocoding_api_key: 'AIzaSyDmNlTvZy0orqhC9wtdYxIP9lTPi0J4rcs'